name: Develop Checks

on:
  pull_request:
    branches: develop
    paths-ignore: 
      - '.github/**'
  push:
    branches: develop
    paths-ignore: 
      - '.github/**'

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - name: Set git auth
      run: git config --global url."https://api:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
    - uses: actions/checkout@v2
    - name: Format check
      run: cargo fmt -- -l --check
    - name: Clippy check
      run: cargo clippy -- -D warnings
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
